name: Generate and Post Tweets

on:
  schedule:
    - cron: '0 0 * * *' # Generate tweets at midnight UTC
    - cron: '0 11,18 * * *' # Post tweets at 11 AM and 6 PM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-tweets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate tweets
        if: github.event.schedule == '0 0 * * *' || github.event_name == 'workflow_dispatch'
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node bot.js

      - name: Upload tweets artifact
        if: github.event.schedule == '0 0 * * *' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4.6.1
        with:
          name: tweets-artifact
          path: tweets.json
          retention-days: 1

  post-tweets:
    needs: generate-tweets
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 11 * * *' || github.event.schedule == '0 18 * * *' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Download tweets artifact
        uses: actions/download-artifact@v4.1.9
        with:
          name: tweets-artifact
          path: .

      - name: Post tweet to Twitter
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node post.js
